### ISSUE TITLE
Throws exception with clojure 1.8.0-RC3

### ISSUE THREAD

**Issue by NoamB** [cdorrat/reduce-fsm#9] opened 2015-12-08 13:13 UTC
Hi,

The line:
(throw (RuntimeException. (str "Could not find the state \"" the-state)) "\"")))

Causes exception:
Exception in thread "main" java.lang.RuntimeException: Too many arguments to throw, throw expects a single Throwable instance, compiling:(reduce_fsm.clj:203:5)

Due to this:
http://dev.clojure.org/jira/browse/CLJ-1456

**Comment by puredanger** [comment] 2015-12-08 14:40
presumably was intended to be 
`(throw (RuntimeException. (str "Could not find the state \"" the-state "\"")))))`

**Comment by cdorrat** [comment] 2015-12-08 20:39
Thanks,
  fixed in version 1.4 & deployed to clojars

**Closed** 2015-12-08 20:39 UTC
